WIP: initial start on lesson
carpentries-incubator/intro-to-modern-fortran pull request #33
Opened 2024-12-16 15:02 UTC by TomMelt

initial start on lesson 01

2025-02-17 13:32 UTC, vahtras commented
Is it intentional not to include this new page in config.yaml? Now its content will not show up when you build/serve the lesson.

2025-03-17 14:53 UTC, TomMelt commented
nope not intentional. It just isn't ready yet. Feel free to add it.

2025-03-19 17:16 UTC, astroDimitrios commented
I have added the file to the config and done some re-writing based on the setup / exercise file layout I am proposing in #34.

2025-03-21 11:45 UTC, dvalters requested changes

2025-03-21 11:45 UTC, dvalters commented on episodes/01-trivial-program.md
> +cd ~/Desktop/intro-to-modern-fortran/01-trivial-program
```suggestion
cd ~/Desktop/intro-to-modern-fortran/exercises/01-trivial-program
```

2025-03-21 14:22 UTC, astroDimitrios commented on episodes/01-trivial-program.md
> +cd ~/Desktop/intro-to-modern-fortran/01-trivial-program
@dvalters The setup instructions for the data set: https://www.astropython.com/intro-to-modern-fortran/index.html#data-sets

mean there is no `exercises` dir when you extract the tar file :)

If this is confusing we can change it.

2025-05-19 09:41 UTC, theabro commented
This looks good to me - the only thing I suggest is defining what IO means - currently it's used on line 83 but is not defined.

2025-05-28 10:57 UTC, vahtras commented
There are to abbreviations for Input/Output, IO and I/O. We should choose one and be consistent throughout the text. I believe I/O is more established.

~~~
episodes/01-trivial-program.md:We will cover IO (Input/Output) in a later episode.
episodes/introduction.Rmd:detail in the context of i/o to external files.
~~~

2025-05-28 12:06 UTC, astroDimitrios commented
> There are to abbreviations for Input/Output, IO and I/O. We should choose one and be consistent throughout the text. I believe I/O is more established.
> 
> ```
> episodes/01-trivial-program.md:We will cover IO (Input/Output) in a later episode.
> episodes/introduction.Rmd:detail in the context of i/o to external files.
> ```

Thanks @vahtras I think we should go with I/O - I have updated the first instance.
You also reminded me that we need to get rid of the `introduction.Rmd` file (which had the old ARCHER2 placeholder content) so I have deleted it :)

2025-06-02 11:22 UTC, astroDimitrios commented on episodes/01-trivial-program.md
> +
```suggestion

The links below may not match your compiler version.
With any documentation make sure it's for your compiler version.

```

2025-06-02 11:24 UTC, astroDimitrios commented on episodes/01-trivial-program.md
> +- [GNU gfortran command options](https://gcc.gnu.org/onlinedocs/gcc-4.3.6/gfortran/Invoking-GNU-Fortran.html#Invoking-GNU-Fortran)
I've added a review comment to say:


The links below may not match your compiler version.
With any documentation make sure it's for your compiler version.

2025-06-11 16:30 UTC, dvalters commented
I shall add a review very soon - sorry I've been away on leave for a while and missed the last session

2026-04-21 14:42 UTC, astroDimitrios commented on episodes/01-trivial-program.md
> +cd ~/Desktop/intro-to-modern-fortran/01-trivial-program
Having re-read this I will change to exercises so that it also matches the git clone download option. I have altered the setup instructions to match. https://github.com/carpentries-incubator/intro-to-modern-fortran/commit/b63e18b5777e1aa41a394c48165ac66269772d8d

2026-04-21 15:08 UTC, astroDimitrios commented
I've addressed the last remaining comment from @dvalters and am going to merge this PR to get things rolling again.
If there are updates to this content based on new feedback from reviewers or from teaching then please open a new Issue.

Thanks everyone for your contributions @TomMelt @warrickball @vahtras @theabro and anyone else I've missed!

2026-04-21 15:08 UTC, merged